plugins {
    id 'java'
    id 'application'
}

group 'org.example'
version '1'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'

    // https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-web
    implementation 'org.springframework.boot:spring-boot-starter-web:2.7.0'
    // https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-test
    testImplementation 'org.springframework.boot:spring-boot-starter-test:2.7.0'
    // https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter
    implementation 'org.springframework.boot:spring-boot-starter:2.7.0'
    // https://mvnrepository.com/artifact/com.google.guava/guava
    //implementation 'com.google.guava:guava:31.1-jre'
    // https://mvnrepository.com/artifact/org.springframework/spring-websocket
    implementation 'org.springframework:spring-websocket:5.3.20'
    // https://mvnrepository.com/artifact/org.springframework/spring-messaging
    implementation 'org.springframework:spring-messaging:5.3.20'
}

test {
    useJUnitPlatform()
}

mainClassName = 'com.websocket.client.ChatClient'

jar {
    manifest {
        attributes ("Main-Class" : mainClassName)
    }
    from {
         configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
jar { duplicatesStrategy(DuplicatesStrategy.EXCLUDE)}